# """
# support_db.py
# ───────────────────────────────────────────────────────────────────────────────
# Backward-compatible facade over the domain modules this file used to
# contain in full (previously ~10,000 lines). All Supabase queries for the
# Support Dashboard now live in the support_db_* modules listed below;
# this file only re-exports their public and private names so every
# existing `from support_db import X` / `support_db.X(...)` call site in
# the rest of the codebase keeps working unchanged.

# Do not add new functions here -- add them to the appropriate domain
# module (support_db_core.py for shared infra; the rest are one file per
# business domain) and re-export the name from this facade.

# Architecture ref: Section 6 (Billing Lifecycle), Section 8 (Schema)
# """

# from logger_config import get_logger

# from support_db_core import (
#     _VALID_TIMEZONES,
#     logger,
#     NODE_HEARTBEAT_INTERVAL_SECONDS,
#     NODE_OFFLINE_THRESHOLD_SAFETY_MULTIPLIER,
#     NODE_OFFLINE_THRESHOLD_MIN_SECONDS,
#     NODE_OFFLINE_THRESHOLD_MAX_SECONDS,
#     NODE_OFFLINE_THRESHOLD_DEFAULT_SECONDS,
#     _VALID_STAFF_WORK_TYPES,
#     _SUPABASE_RETRYABLE_MARKERS,
#     _TENANT_META_CACHE_TTL_SECONDS,
#     _STATUS_CACHE_TTL_SECONDS,
#     _ORG_CACHE,
#     _BRANCH_CACHE,
#     _STATUS_CACHE,
#     _validate_branch_timezone,
#     _is_retryable_supabase_error,
#     _execute_supabase,
#     _cache_get,
#     _cache_set,
#     _cache_set_for,
#     _invalidate_tenant_meta_cache,
#     get_internal_user_by_id,
#     _compute_org_status,
#     _org_access_allows_client,
#     _ensure_org_client_access,
#     _json_dict,
#     _attach_status,
#     _json_list,
# )
# from support_db_organizations import (
#     list_vertical_templates,
#     _with_vertical_defaults,
#     list_organizations,
#     get_organization,
#     create_organization,
#     update_organization,
#     update_organization_template,
#     _normalize_staff_type_scope,
#     update_organization_staff_type_scope,
#     _VALID_RETENTION_YEARS,
#     _normalize_org_retention_years,
#     _retention_until_from_years,
#     archive_organization,
#     restore_organization,
#     update_organization_retention_policy,
#     request_organization_delete,
#     _postgrest_error_payload,
#     _delete_error_is_schema_mismatch,
#     _delete_rows_for_org,
#     _delete_rows_for_branch_ids,
#     _load_org_branch_ids_for_delete,
#     permanently_delete_organization,
# )
# from support_db_branches import (
#     list_branches,
#     create_branch,
#     _count_active_people_for_branch,
#     _get_branch_for_update,
#     update_branch,
#     _unique_text_ids,
#     drop_organization_branches_for_limit,
#     _validate_branch_limit_decrease,
#     create_client_branch_install_token,
#     list_org_modules,
#     set_org_modules,
#     toggle_module,
# )
# from support_db_billing import (
#     get_subscription,
#     upsert_subscription,
#     list_invoices,
#     create_invoice,
#     mark_invoice_paid,
# )
# from support_db_nodes import (
#     get_node_health,
#     _resolve_node_offline_threshold_seconds,
#     _compute_node_status,
#     set_fallback,
#     _sha256_secret,
#     _token,
#     _iso_now,
#     _parse_dt,
#     _get_branch_owned_by_org,
#     create_branch_install_token,
#     activate_node_with_install_token,
#     get_node_by_api_key,
#     node_heartbeat,
#     get_local_node_status,
#     get_recent_fallback_attendance,
#     _local_node_camera_view,
#     get_node_config,
#     poll_node_training_jobs,
#     _replace_face_embeddings_cloud,
#     _LOCAL_NODE_EMBEDDING_SOFT_MIN,
#     _valid_embedding_list,
#     mark_node_training_job_trained,
#     _node_attendance_metadata,
#     push_node_attendance,
#     push_node_embeddings,
#     get_staff_face_embeddings,
#     get_org_recognition_embeddings,
#     record_cloud_camera_attendance,
# )
# from support_db_client_users import (
#     _CLIENT_MODULE_MAP,
#     _VALID_MODULES,
#     _MODULE_ALIASES,
#     _normalise_module_name,
#     _map_module_for_client,
#     _safe_client_user,
#     _generate_temp_password,
#     _hash_password,
#     _verify_password,
#     _active_client_modules,
#     _normalize_branch_module_people_type_entries,
#     list_branch_module_people_types,
#     set_branch_module_people_types,
#     list_org_branch_module_people_types,
#     _seed_default_branch_module_people_types,
#     _latest_invoice,
#     _default_people_kind_for_biz,
#     _normalize_people_kind,
#     _build_client_config,
#     create_client_invite,
#     _client_user_session_from_row,
#     get_client_user_session_by_id,
#     authenticate_client_user,
#     _find_active_client_staff_row,
#     _touch_client_staff_last_login,
#     authenticate_client_staff,
#     authenticate_client_staff_for_dashboard,
#     get_client_onboarding_config,
#     _branch_maps,
#     _ui_branch_key,
#     _normalize_named_items_by_branch,
#     _normalize_cameras_by_branch,
#     _merge_operational_config,
#     get_client_bootstrap,
#     _branch_backend_id,
#     _normalize_branch_keyed_config,
#     _clean_optional_text,
#     _first_present,
#     _int_or_default,
#     _bool_or_default,
#     _branch_network_from_config,
#     _VALID_CAMERA_TYPES,
#     _normalize_camera_type,
#     _normalize_local_node_camera_row,
#     _sync_local_node_camera_config,
#     _extract_company_profile,
#     save_client_onboarding_config,
#     _person_code_from_payload,
#     _person_code_label,
#     _assert_unique_client_staff_person_code,
#     _assert_unique_client_staff_login_identifier,
#     update_client_user_profile,
# )
# from support_db_staff import (
#     _safe_float,
#     _haversine_distance_meters,
#     _client_branch_indexes,
#     _resolve_client_branch,
#     _branch_ui_id,
#     CLIENT_STAFF_ACCOUNT_ROLES,
#     _CLIENT_STAFF_HAS_PEOPLE_TYPE_COLUMN,
#     _normalize_people_type,
#     _normalize_account_role,
#     _client_staff_has_people_type_column,
#     _staff_filter_parts,
#     _resolve_shift_map,
#     _client_staff_safe,
#     _next_employee_id,
#     list_client_staff,
#     get_client_staff_member,
#     _count_active_staff_for_branch,
#     create_client_staff,
#     update_client_staff,
#     archive_client_staff,
#     restore_client_staff,
#     delete_client_staff,
#     update_client_staff_photo,
#     create_face_training_job_for_staff,
#     _normalize_employee_retention_years,
#     get_employee_retention_policy,
#     update_employee_retention_policy,
# )
# from support_db_attendance_mobile import (
#     _resolve_client_staff_attendance_window,
#     get_client_staff_attendance_today,
#     _check_action_replay,
#     mark_client_staff_attendance,
#     evaluate_field_geofence,
#     mark_field_staff_attendance,
#     record_field_geo_alert,
# )
# from support_db_attendance_dashboard import (
#     _dashboard_day_window_utc,
#     _resolve_attendance_branch_id,
#     _attendance_row_for_dashboard,
#     _client_attendance_rows,
#     get_client_staff_attendance_history,
#     get_client_attendance_today,
#     get_client_attendance_logs,
#     get_client_attendance_statistics,
#     mark_client_staff_absent_today,
#     _EDITABLE_ATTENDANCE_STATUS_VALUES,
#     update_client_attendance_record,
#     complete_face_training_job_from_dashboard,
#     _support_clean_text,
#     _resolve_owned_backend_branch_id,
#     list_client_cameras,
#     get_client_camera_by_id,
#     _client_staff_lookup,
#     _resolve_staff_people_type,
#     _map_client_leave,
#     list_client_leave_requests,
# )
# from support_db_payroll import (
#     _DEFAULT_PAYROLL_POLICY,
#     _org_default_payroll_policy,
#     _payroll_policy_override,
#     resolve_effective_ot_rate,
#     resolve_effective_allowances,
#     get_payroll_policy,
#     get_leave_type_rules,
#     get_leave_type_allocations,
#     save_payroll_policy,
#     get_paid_payroll_periods,
#     mark_payroll_paid,
#     mark_payroll_pending,
#     _PAYROLL_ATTENDANCE_COLUMNS_BASE,
#     _PAYROLL_ATTENDANCE_COLUMNS_WITH_DECISION,
#     get_staff_attendance_for_payroll_period,
#     get_approved_leaves_for_payroll_period,
#     get_approved_overtime_hours_for_payroll_period,
#     get_local_node_overtime_hours_for_payroll_period,
#     create_client_leave_request,
#     get_client_leave_owned_by_org,
#     update_client_leave_status,
#     delete_client_leave_request,
#     _map_client_overtime,
#     list_client_overtime_requests,
#     create_client_overtime_request,
#     get_client_overtime_owned_by_org,
#     update_client_overtime_status,
#     get_client_branch_summary,
#     _payroll_text,
#     _payroll_float,
#     _payroll_positive_int,
#     _payroll_sort_column,
#     _payroll_page_row,
#     get_client_payroll_page,
# )
# from support_db_dashboard_summary import (
#     _resolve_fast_summary_branch_id,
#     _fast_summary_fallback,
#     get_tenant_fast_summary,
#     _DASHBOARD_SNAPSHOT_CACHE_TTL_SECONDS,
#     _DASHBOARD_SNAPSHOT_CACHE,
#     _dashboard_text,
#     _dashboard_float,
#     _dashboard_int,
#     _dashboard_round,
#     _dashboard_cache_key,
#     _dashboard_cache_get,
#     _dashboard_cache_set,
#     _dashboard_branch_maps,
#     _dashboard_week_days,
#     _dashboard_month_labels,
#     _dashboard_identity,
#     _dashboard_branch_uuid,
#     _dashboard_staff_rows,
#     _dashboard_real_shift_distribution,
#     _dashboard_weekly_from_attendance,
#     _dashboard_performance_from_totals,
#     _dashboard_payroll_trend,
#     _dashboard_live_log,
#     _dashboard_pending_leaves,
#     _dashboard_cctv_status,
#     get_client_dashboard_overview,
# )
# from support_db_internal import (
#     _support_page_int,
#     _support_page_window,
#     _support_paginated,
#     _support_text,
#     _support_lower,
#     _support_org_lookup,
#     _support_search_match,
#     _support_filter_page_rows,
#     list_support_branches_page,
#     list_support_invoices_page,
#     list_support_module_entitlements_page,
#     list_support_node_health_page,
#     run_offline_detection_sweep,
#     _safe_internal_user,
#     list_internal_users_page,
#     _INTERNAL_USER_ROLES,
#     _INTERNAL_USER_ROLE_ALIASES,
#     _normalize_internal_user_role,
#     create_internal_user,
#     update_internal_user,
#     reset_internal_user_password,
#     get_camera_recognition_status,
#     import_embeddings_cloud_mode,
# )

# from support_db_attendance_gate import (
#     resolve_timing_source,
#     resolve_manual_instruction_window,
#     resolve_branch_default_window,
#     resolve_staff_shift_windows,
#     resolve_check_in_status,
#     resolve_check_out_status,
#     _get_branch_timezone,
#     _find_approved_overtime,
# )
# from support_db_attendance_settings import list_pending_manual_instructions_for_branch
# from support_db_time_utils import is_missing_table_or_column as _table_missing
# import support_db_attendance_exceptions as _attendance_exceptions

# logger = get_logger(__name__)


"""
support_db.py
───────────────────────────────────────────────────────────────────────────────
Backward-compatible facade over the domain modules this file used to
contain in full (previously ~10,000 lines). All Supabase queries for the
Support Dashboard now live in the support_db_* modules listed below;
this file only re-exports their public and private names so every
existing `from support_db import X` / `support_db.X(...)` call site in
the rest of the codebase keeps working unchanged.

Do not add new functions here -- add them to the appropriate domain
module (support_db_core.py for shared infra; the rest are one file per
business domain) and re-export the name from this facade.

Architecture ref: Section 6 (Billing Lifecycle), Section 8 (Schema)
"""

from logger_config import get_logger

from support_db_core import (
    _VALID_TIMEZONES,
    logger,
    NODE_HEARTBEAT_INTERVAL_SECONDS,
    NODE_OFFLINE_THRESHOLD_SAFETY_MULTIPLIER,
    NODE_OFFLINE_THRESHOLD_MIN_SECONDS,
    NODE_OFFLINE_THRESHOLD_MAX_SECONDS,
    NODE_OFFLINE_THRESHOLD_DEFAULT_SECONDS,
    _VALID_STAFF_WORK_TYPES,
    _SUPABASE_RETRYABLE_MARKERS,
    _TENANT_META_CACHE_TTL_SECONDS,
    _STATUS_CACHE_TTL_SECONDS,
    _ORG_CACHE,
    _BRANCH_CACHE,
    _STATUS_CACHE,
    _validate_branch_timezone,
    _is_retryable_supabase_error,
    _execute_supabase,
    _cache_get,
    _cache_set,
    _cache_set_for,
    _invalidate_tenant_meta_cache,
    get_internal_user_by_id,
    _compute_org_status,
    _org_access_allows_client,
    _ensure_org_client_access,
    _json_dict,
    _attach_status,
    _json_list,
)
from support_db_organizations import (
    list_vertical_templates,
    _with_vertical_defaults,
    list_organizations,
    get_organization,
    create_organization,
    update_organization,
    update_organization_template,
    _normalize_staff_type_scope,
    update_organization_staff_type_scope,
    _VALID_RETENTION_YEARS,
    _normalize_org_retention_years,
    _retention_until_from_years,
    archive_organization,
    restore_organization,
    update_organization_retention_policy,
    request_organization_delete,
    _postgrest_error_payload,
    _delete_error_is_schema_mismatch,
    _delete_rows_for_org,
    _delete_rows_for_branch_ids,
    _load_org_branch_ids_for_delete,
    permanently_delete_organization,
)
from support_db_branches import (
    list_branches,
    create_branch,
    _count_active_people_for_branch,
    _get_branch_for_update,
    update_branch,
    _unique_text_ids,
    drop_organization_branches_for_limit,
    _validate_branch_limit_decrease,
    create_client_branch_install_token,
    list_org_modules,
    set_org_modules,
    toggle_module,
)
from support_db_billing import (
    get_subscription,
    upsert_subscription,
    list_invoices,
    create_invoice,
    mark_invoice_paid,
)
from support_db_nodes import (
    get_node_health,
    _resolve_node_offline_threshold_seconds,
    _compute_node_status,
    set_fallback,
    _sha256_secret,
    _token,
    _iso_now,
    _parse_dt,
    _get_branch_owned_by_org,
    create_branch_install_token,
    activate_node_with_install_token,
    get_node_by_api_key,
    node_heartbeat,
    get_local_node_status,
    get_recent_fallback_attendance,
    get_recent_fallback_attendance_bulk,
    _local_node_camera_view,
    get_node_config,
    poll_node_training_jobs,
    _replace_face_embeddings_cloud,
    _LOCAL_NODE_EMBEDDING_SOFT_MIN,
    _valid_embedding_list,
    mark_node_training_job_trained,
    _node_attendance_metadata,
    push_node_attendance,
    push_node_embeddings,
    get_staff_face_embeddings,
    get_org_recognition_embeddings,
    record_cloud_camera_attendance,
)
from support_db_client_users import (
    _CLIENT_MODULE_MAP,
    _VALID_MODULES,
    _MODULE_ALIASES,
    _normalise_module_name,
    _map_module_for_client,
    _safe_client_user,
    _generate_temp_password,
    _hash_password,
    _verify_password,
    _active_client_modules,
    _normalize_branch_module_people_type_entries,
    list_branch_module_people_types,
    set_branch_module_people_types,
    list_org_branch_module_people_types,
    _seed_default_branch_module_people_types,
    _latest_invoice,
    _default_people_kind_for_biz,
    _normalize_people_kind,
    _build_client_config,
    create_client_invite,
    _client_user_session_from_row,
    get_client_user_session_by_id,
    get_client_user_basic,
    authenticate_client_user,
    _find_active_client_staff_row,
    _touch_client_staff_last_login,
    authenticate_client_staff,
    authenticate_client_staff_for_dashboard,
    get_client_onboarding_config,
    _branch_maps,
    _ui_branch_key,
    _normalize_named_items_by_branch,
    _normalize_cameras_by_branch,
    _merge_operational_config,
    get_client_bootstrap,
    _branch_backend_id,
    _normalize_branch_keyed_config,
    _clean_optional_text,
    _first_present,
    _int_or_default,
    _bool_or_default,
    _branch_network_from_config,
    _VALID_CAMERA_TYPES,
    _normalize_camera_type,
    _normalize_local_node_camera_row,
    _sync_local_node_camera_config,
    _extract_company_profile,
    save_client_onboarding_config,
    _person_code_from_payload,
    _person_code_label,
    _assert_unique_client_staff_person_code,
    _assert_unique_client_staff_login_identifier,
    update_client_user_profile,
    change_own_dashboard_password,
    validate_strong_password,
)
from support_db_staff import (
    _safe_float,
    _haversine_distance_meters,
    _client_branch_indexes,
    _resolve_client_branch,
    _branch_ui_id,
    CLIENT_STAFF_ACCOUNT_ROLES,
    _CLIENT_STAFF_HAS_PEOPLE_TYPE_COLUMN,
    _normalize_people_type,
    _normalize_account_role,
    _client_staff_has_people_type_column,
    _staff_filter_parts,
    _resolve_shift_map,
    _client_staff_safe,
    _next_employee_id,
    list_client_staff,
    get_client_staff_member,
    _count_active_staff_for_branch,
    create_client_staff,
    update_client_staff,
    archive_client_staff,
    restore_client_staff,
    delete_client_staff,
    update_client_staff_photo,
    create_face_training_job_for_staff,
    _normalize_employee_retention_years,
    get_employee_retention_policy,
    update_employee_retention_policy,
)
from support_db_attendance_mobile import (
    _resolve_client_staff_attendance_window,
    get_client_staff_attendance_today,
    _check_action_replay,
    mark_client_staff_attendance,
    evaluate_field_geofence,
    mark_field_staff_attendance,
    record_field_geo_alert,
)
from support_db_attendance_dashboard import (
    _dashboard_day_window_utc,
    _resolve_attendance_branch_id,
    _attendance_row_for_dashboard,
    _client_attendance_rows,
    get_client_staff_attendance_history,
    get_client_attendance_today,
    get_client_attendance_logs,
    get_client_attendance_statistics,
    mark_client_staff_absent_today,
    _EDITABLE_ATTENDANCE_STATUS_VALUES,
    update_client_attendance_record,
    complete_face_training_job_from_dashboard,
    _support_clean_text,
    _resolve_owned_backend_branch_id,
    list_client_cameras,
    get_client_camera_by_id,
    _client_staff_lookup,
    _resolve_staff_people_type,
    _map_client_leave,
    list_client_leave_requests,
)
from support_db_payroll import (
    _DEFAULT_PAYROLL_POLICY,
    _org_default_payroll_policy,
    _payroll_policy_override,
    resolve_effective_ot_rate,
    resolve_effective_allowances,
    get_payroll_policy,
    get_leave_type_rules,
    get_leave_type_allocations,
    save_payroll_policy,
    get_paid_payroll_periods,
    mark_payroll_paid,
    mark_payroll_pending,
    _PAYROLL_ATTENDANCE_COLUMNS_BASE,
    _PAYROLL_ATTENDANCE_COLUMNS_WITH_DECISION,
    get_staff_attendance_for_payroll_period,
    get_approved_leaves_for_payroll_period,
    get_approved_overtime_hours_for_payroll_period,
    get_local_node_overtime_hours_for_payroll_period,
    create_client_leave_request,
    get_client_leave_owned_by_org,
    update_client_leave_status,
    delete_client_leave_request,
    _map_client_overtime,
    list_client_overtime_requests,
    create_client_overtime_request,
    get_client_overtime_owned_by_org,
    update_client_overtime_status,
    get_client_branch_summary,
    _payroll_text,
    _payroll_float,
    _payroll_positive_int,
    _payroll_sort_column,
    _payroll_page_row,
    get_client_payroll_page,
)
from support_db_dashboard_summary import (
    _resolve_fast_summary_branch_id,
    _fast_summary_fallback,
    get_tenant_fast_summary,
    _DASHBOARD_SNAPSHOT_CACHE_TTL_SECONDS,
    _DASHBOARD_SNAPSHOT_CACHE,
    _dashboard_text,
    _dashboard_float,
    _dashboard_int,
    _dashboard_round,
    _dashboard_cache_key,
    _dashboard_cache_get,
    _dashboard_cache_set,
    _dashboard_branch_maps,
    _dashboard_week_days,
    _dashboard_month_labels,
    _dashboard_identity,
    _dashboard_branch_uuid,
    _dashboard_staff_rows,
    _dashboard_real_shift_distribution,
    _dashboard_weekly_from_attendance,
    _dashboard_performance_from_totals,
    _dashboard_payroll_trend,
    _dashboard_live_log,
    _dashboard_pending_leaves,
    _dashboard_cctv_status,
    get_client_dashboard_overview,
)
from support_db_internal import (
    _support_page_int,
    _support_page_window,
    _support_paginated,
    _support_text,
    _support_lower,
    _support_org_lookup,
    _support_search_match,
    _support_filter_page_rows,
    list_support_branches_page,
    list_support_invoices_page,
    list_support_module_entitlements_page,
    list_support_node_health_page,
    run_offline_detection_sweep,
    _safe_internal_user,
    list_internal_users_page,
    _INTERNAL_USER_ROLES,
    _INTERNAL_USER_ROLE_ALIASES,
    _normalize_internal_user_role,
    create_internal_user,
    update_internal_user,
    reset_internal_user_password,
    get_camera_recognition_status,
    import_embeddings_cloud_mode,
)

from support_db_attendance_gate import (
    resolve_timing_source,
    resolve_manual_instruction_window,
    resolve_branch_default_window,
    resolve_staff_shift_windows,
    resolve_check_in_status,
    resolve_check_out_status,
    _get_branch_timezone,
    _find_approved_overtime,
)
from support_db_attendance_settings import list_pending_manual_instructions_for_branch
from support_db_time_utils import is_missing_table_or_column as _table_missing
import support_db_attendance_exceptions as _attendance_exceptions

logger = get_logger(__name__)